config/routes.rb
Rails.application.routes.draw do
  resources :my_avatars

  devise_for :users
  root 'pages#home'

  get "about" => "pages#about"

  put "/pages/:id/update_avatar_attribute" => "pages#update_avatar_attribute", as:"update_avatar_attribute"

  resources :general_quests

end

app/models/general_quest.rb
class GeneralQuest < ActiveRecord::Base

end

app/models/my_avatar.rb
class MyAvatar < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x390", :thumb => "100x130" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :my_avatar, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/general_quests_controller.rb
class GeneralQuestsController < ApplicationController
	def index
		# will have template
		@quests = GeneralQuest.all
	end

	def new # display the for new record
		# will have template
		@quest = GeneralQuest.new
	end

	def create # save new record
		# will save and redirect
		@quest = GeneralQuest.new(allowed_params)
		if @quest.save
			redirect_to general_quests_path
		else
			render 'new'
		end

	end

	def edit # display form for editing record
		# will save and redirect
		@quest = GeneralQuest.find(params[:id])
	end

	def update # save changes
		# will save and redirect
		@quest = GeneralQuest.find(params[:id])
		if @quest.update_attributes(allowed_params)
			@quest.save
			puts(allowed_params)
			redirect_to general_quests_path
		else
			render 'update'
		end

	end

	def destroy
		# will destroy and redirect
		@quest = GeneralQuest.find(params[:id])
		@quest.destroy
		redirect_to general_quests_path
	end

	def get_strength_quests
		return GeneralQuest.where(category: "health")
	end
	
	private 
		def allowed_params
			params.require(:general_quest).permit(:category, :title, :description, :experience, :available)
		end

end

app/controllers/my_avatars_controller.rb
class MyAvatarsController < ApplicationController
  before_action :set_my_avatar, only: [:show, :edit, :update, :destroy] 
  before_action :authenticate_user!

  respond_to :html

  def index
    @my_avatars = MyAvatar.where(user_id: current_user)
    respond_with(@my_avatars)
  end

  def show
    respond_with(@my_avatar)
  end

  def new
      @my_avatar = MyAvatar.new
      respond_with(@my_avatar)
  end

  def edit
  end

  def create
    @my_avatar = MyAvatar.new(my_avatar_params)
    @my_avatar.user_id = current_user.id
    @my_avatar.save
    respond_with(@my_avatar)
  end

  def update
    @my_avatar.update(my_avatar_params)
    respond_with(@my_avatar)
  end

  def destroy
    @my_avatar.destroy
    respond_with(@my_avatar)
  end

  private
    def set_my_avatar
      @my_avatar = MyAvatar.find(params[:id])
    end

    def my_avatar_params
      params.require(:my_avatar).permit(:health_xp, :stamina_xp, :strength_xp, :intelligence, :user_id, :name, :image)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  	if user_signed_in?
  		@healthQuests = GeneralQuest.where(category: "health")
  		@staminaQuests = GeneralQuest.where(category: "stamina")
  		@strengthQuests = GeneralQuest.where(category: "strength")
  		@intelligenceQuests = GeneralQuest.where(category: "intelligence")

  		unless User.find(current_user.id).my_avatar
  			redirect_to new_my_avatar_path
  		end
  		@myAvatar = User.find(current_user.id).my_avatar 
  	end
  end

  def update_avatar_attribute
    @quest = GeneralQuest.find(params[:id])
    @category = @quest.category
    @avatar = User.find(current_user.id).my_avatar
    @quest_title = @quest.title
    case @category
    when "health"
      @new_exp = @avatar.health_xp + @quest.experience
      @avatar.health_xp = @new_exp
    when "stamina"
      @new_exp = @avatar.stamina_xp + @quest.experience
      @avatar.stamina_xp = @new_exp
    when "strength"
      @new_exp = @avatar.strength_xp + @quest.experience
      @avatar.strength_xp = @new_exp
    else 
      @new_exp = @avatar.intelligence_xp + @quest.experience
      @avatar.intelligence_xp = @new_exp
    end
    @avatar.save
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_quests_helper.rb
module GeneralQuestsHelper
end

app/helpers/my_avatars_helper.rb
module MyAvatarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/general_quests/edit.html.erb
<body>
	<%= form_for @quest do |f| %>
		
		<%= f.label "Category"%> <br />

		<%= f.radio_button :category, "health" %><%= f.label "Health" %>
		<%= f.radio_button :category, "strength" %><%= f.label "Strength" %>
		<%= f.radio_button :category, "stamina" %><%= f.label "Stamina" %>
		<%= f.radio_button :category, "intelligence" %><%= f.label "Intelligence" %><br />
		<br />

		<%= f.label :title%> <br />
		<%= f.text_field :title %> <br />

		<br />

		<%= f.label :description%> <br />
		<%= f.text_field :description %> <br />

		<br />

		<%= f.label :experience%> <br />
		<%= f.text_field :experience %> <br />

		<br />

		<%= f.check_box :available %> 
		<%= f.label "Make Quest Available" %> <br />

		<%= f.submit 'Update Quest'%>
	<% end %>
<br />

app/views/general_quests/index.html.erb
<%= link_to 'Add Quest', new_general_quest_path %>
<% questNumber = 1 %>
<% @quests.each do |quest| %>
	<h4>Quest <%= questNumber %></h4>
	<p>
		Category: <%= quest.category %> <br />
		Title: <%= quest.title %> <br />
		Descripttion: <%= quest.description %> <br />
		Experience: <%= quest.experience %> <br />
		<% if quest.available %>
			Available: <%= "Yes" %>
		<% else %>
			Available: <%= "No" %>
		<% end %>
		<br />
		<%= link_to 'Edit', edit_general_quest_path(quest) %>  
		<%= link_to 'Delete', quest, method: :delete %> <br />
	</p>
	<% questNumber += 1 %>
<% end %>

app/views/general_quests/new.html.erb
<body>
	<%= form_for @quest do |f| %>
		
		<%= f.label "Category"%> <br />

		<%= f.radio_button :category, "health" %><%= f.label "Health" %>
		<%= f.radio_button :category, "strength" %><%= f.label "Strength" %>
		<%= f.radio_button :category, "stamina" %><%= f.label "Stamina" %>
		<%= f.radio_button :category, "intelligence" %><%= f.label "Intelligence" %><br />
		<br />

		<%= f.label :title%> <br />
		<%= f.text_field :title %> <br />

		<br />

		<%= f.label :description%> <br />
		<%= f.text_field :description %> <br />

		<br />

		<%= f.label :experience%> <br />
		<%= f.text_field :experience %> <br />

		<br />

		<%= f.check_box :available %> 
		<%= f.label "Make Quest Available" %> <br />

		<%= f.submit 'Save Quest'%>
	<% end %>
<br />

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Avatar</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li> 
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avatar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
		<%= yield %>
	</div>

<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>

</body>
</html>

app/views/my_avatars/_form.html.erb
<%= form_for @my_avatar, html: { multipart: true } do |f| %>
  <% if @my_avatar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_avatar.errors.count, "error") %> prohibited this my_avatar from being saved:</h2>

      <ul>
      <% @my_avatar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Avatar Starting Experience</h4>
    <p>Health = 0</p>
    <p>Stamina = 0</p>
    <p>Strength = 0</p>
    <p>Intelligence = 0</p>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %></br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_avatars/edit.html.erb
<h1>Editing My Avatar</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_avatar %> |
<%= link_to 'Back', my_avatars_path %>

app/views/my_avatars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing My Avatars</h1>

<table>
  <thead>
    <tr>
      <th>Health xp</th>
      <th>Stamina xp</th>
      <th>Strength xp</th>
      <th>Intelligence xp</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_avatars.each do |my_avatar| %>
      <tr>
        <td><%= my_avatar.health_xp %></td>
        <td><%= my_avatar.stamina_xp %></td>
        <td><%= my_avatar.strength_xp %></td>
        <td><%= my_avatar.intelligence_xp %></td>
        <td><%= my_avatar.user_id %></td>
        <td><%= link_to 'Show', my_avatar %></td>
        <td><%= link_to 'Edit', edit_my_avatar_path(my_avatar) %></td>
        <td><%= link_to 'Destroy', my_avatar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My avatar', new_my_avatar_path %>

app/views/my_avatars/new.html.erb
<h1>New My Avatar</h1>

<%= render 'form' %>

<%= link_to 'Back', my_avatars_path %>

app/views/my_avatars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Health xp:</strong>
  <%= @my_avatar.health_xp %>
</p>

<p>
  <strong>Stamina xp:</strong>
  <%= @my_avatar.stamina_xp %>
</p>

<p>
  <strong>Strength xp:</strong>
  <%= @my_avatar.strength_xp %>
</p>

<p>
  <strong>Intelligence xp:</strong>
  <%= @my_avatar.intelligence_xp %>
</p>

<p>
  <strong>User:</strong>
  <%= @my_avatar.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @my_avatar.name %>
</p>
<p>
  <strong>Avatar Image:</strong></br>
  <%= image_tag @my_avatar.image.url(:medium) %>
</p>
<%= link_to 'Edit', edit_my_avatar_path(@my_avatar) %> |
<%= link_to 'Back', my_avatars_path %>

app/views/pages/about.html.erb
<%= link_to "Home", root_path %>
<%= link_to "About", about_path %>
<h1>About US</h1>
<p>We are working on our One Month Rails Pinteresting app</p>

app/views/pages/home.html.erb
<body>
<% if user_signed_in? %>
<div id="avatar container">

	<h4> <%= @myAvatar.name %> </h4>
		<%= image_tag @myAvatar.image.url(:thumb) %>
		<p> 
			Health = <div class="health"><%= @myAvatar.health_xp %></div> 
		</p>
		<p> 
			Stamina = <div class="stamina"><%= @myAvatar.stamina_xp %></div>
		</p>
		<p> 
			Strength = <div class="strength"><%= @myAvatar.strength_xp %></div>
		</p>
		<p> 
			Intelligence = <div class="intelligence"><%= @myAvatar.intelligence_xp %></div>
		</p>
	</div>
<div id="wrapper">

	<div role="tabpanel">
		<ul class="nav nav-tabs" role="tablist">
			<li role="presentation" class="active">
				<a href="#health" aria-controls="health" role="tab" data-toggle="tab">Health</a>
			</li>
			<li role="presentation">
				<a href="#stamina" aria-controls="stamina" role="tab" data-toggle="tab">Stamina</a>
			</li>
			<li role="presentation">
				<a href="#strength" aria-controls="strength" role="tab" data-toggle="tab">Strength</a>
			</li>
			<li role="presentation">
				<a href="#intelligence" aria-controls="intelligence" role="tab" data-toggle="tab">Intelligence</a>
			</li>
		</ul>
		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="health">
				<% @healthQuests.each do |quest| %>
					<h2 class="accordion"></a href="#"> <%= quest.title %> </a></h2>
					<div class="accContainer">
						<p> <%= quest.description %> </p>
						<p> exp = <%= quest.experience %></p>
						<%= link_to "complete", { action: "update_avatar_attribute", id: quest.id }, method: :put, remote: true,:format => 'js' %>
					</div>
				<% end %>
			</div>
			<div role="tabpanel" class="tab-pane" id="stamina">
				<% @staminaQuests.each do |quest| %>
					<h2 class="accordion"></a href="#"> <%= quest.title %> </a></h2>
					<div class="accContainer">
						<p> <%= quest.description %> </p>
						<p> exp = <%= quest.experience %></p>
						<%= link_to "complete", { action: "update_avatar_attribute", id: quest.id }, method: :put, remote: true,:format => 'js' %>
					</div>
				<% end %>
			</div>
			<div role="tabpanel" class="tab-pane" id="strength">
				<% @strengthQuests.each do |quest| %>
					<h2 class="accordion"></a href="#"> <%= quest.title %> </a></h2>
					<div class="accContainer">
						<p> <%= quest.description %> </p>
						<p> exp = <%= quest.experience %></p>
						<%= link_to "complete", { action: "update_avatar_attribute", id: quest.id }, method: :put, remote: true,:format => 'js' %>
					</div>
				<% end %>
			</div>
			<div role="tabpanel" class="tab-pane" id="intelligence">
				<% @intelligenceQuests.each do |quest| %>
					<h2 class="accordion"></a href="#"> <%= quest.title %> </a></h2>
					<div class="accContainer">
						<p> <%= quest.description %> </p>
						<p> exp = <%= quest.experience %></p>
						<%= link_to "complete", { action: "update_avatar_attribute", id: quest.id }, method: :put, remote: true,:format => 'js' %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>
<% else %>
	<div class="jumbotron center">
	  <h1>Welcome to Avatar</h1>
	  <p>
	    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
	    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	  </p>  
	</div>
<% end %>
</body>

app/views/pages/update_avatar_attribute.js.erb
<% case @category %>
<% when "health" %>
	$('.health').html(<%= @new_exp %>);
<% when "stamina" %>
	$('.stamina').html(<%= @new_exp %>);
<% when "strength" %>
	$('.strength').html(<%= @new_exp %>);
<% else "intelligence" %>
	$('.intelligence').html(<%= @new_exp %>);
<% end %>
alert("Completed <%= @quest_title %>");